## Synthetic Data relabeling

In [1]:
## Relabel the synthetic data using GPT-4o

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="3"
os.environ["TOKENIZERS_PARALLELISM"]="false"

In [15]:
import pandas as pd
from src.utils.script_utils import init_population_from_df, init_population_from_dump
from src.utils.script_utils import get_datasets
path="sync_data"
dtype="ClaudeFewShot"
#dataset="lfqa-veri"
#dataset="summedits"
dataset="ragtruth"
g="QA"
#g="news"

dtrain, _ , _ = get_datasets(dataset, g)
#pop_init = init_population_from_df(dtrain.df)

synth_data_train = pd.read_csv(f"{path}/{dtype}_{dataset}-{g}_relabel_gpt4o.csv")
pop_sync = init_population_from_dump(synth_data_train, use_evidence=list(dtrain.df.evidence.unique()), quantile_scores=True)

Token indices sequence length is longer than the specified maximum sequence length for this model (1047 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1041 > 1024). Running this sequence through the model will result in indexing errors


In [9]:
from src.sync_data.initial_generators import FromFile

In [10]:
data = FromFile(type="ClaudeFewShot", path="sync_data", dataset="ragtruth", group="Summary", entail_model="quantile")

Summary


In [16]:
pop_sync.to_dataframe()

tag_0  tag_1  \
0      Briefly answer the following question:\ntips h...      0   
1      Briefly answer the following question:\ntips h...      0   
2      Briefly answer the following question:\ntips h...      0   
3      Briefly answer the following question:\ntips h...      0   
4      Briefly answer the following question:\ntips h...      0   
...                                                  ...    ...   
20103  Briefly answer the following question:\nwhat a...      1   
20104  Briefly answer the following question:\nwhat a...      1   
20105  Briefly answer the following question:\nwhat a...      1   
20106  Briefly answer the following question:\nwhat a...      1   
20107  Briefly answer the following question:\nwhat a...      1   

                                                  sample  ref  p_agree  \
0      Here are some tips to conserve water based on ...    0      1.0   
1      Here are some tips to conserve water based on ...    1      1.0   
2      Here are some water-saving tips based on the p...    2      1.0   
3      Here are some tips to conserve water based on ...    3      1.0   
4      To conserve water, you can take shorter shower...    4      1.0   
...                                                  ...  ...      ...   
20103  Based on the provided passages, here are the n...   11      1.0   
20104  Based on the given passages, here are some of ...   12      1.0   
20105  Eating tomatoes has several nutritional benefi...   13      1.0   
20106  Based on the given passages, it appears that e...   14      1.0   
20107  According to the given passages, eating tomato...   15      1.0   

         p_init  
0      0.191068  
1      0.028645  
2      0.175353  
3      0.159389  
4      0.039885  
...         ...  
20103  0.500000  
20104  0.661329  
20105  0.795604  
20106  0.800627  
20107  0.999950  

[20108 rows x 6 columns]

In [12]:
res.to_dataframe().p_init[32:64]

32    0.167934
33    0.124718
34    0.128730
35    0.218117
36    0.941934
37    0.769355
38    0.928561
39    0.974592
40    0.105152
41    0.299198
42    0.222551
43    0.309685
44    0.950310
45    0.618525
46    0.871059
47    0.912655
48    0.486909
49    0.272311
50    0.500000
51    0.500000
52    0.865850
53    0.892807
54    0.786036
55    0.500000
56    0.025267
57    0.159276
58    0.166104
59    0.049690
60    0.772593
61    0.851633
62    0.824043
63    0.882742
Name: p_init, dtype: float64

In [29]:
float("2.2e-05")

2.2e-05

In [28]:
synth_data_train[:16]

Unnamed: 0                                              tag_0  tag_1  \
0            0  Andrew Getty, one of the heirs to billions of ...      0   
1            1  Andrew Getty, one of the heirs to billions of ...      0   
2            2  Andrew Getty, one of the heirs to billions of ...      0   
3            3  Andrew Getty, one of the heirs to billions of ...      0   
4            4  Andrew Getty, one of the heirs to billions of ...      0   
5            5  Andrew Getty, one of the heirs to billions of ...      0   
6            6  Andrew Getty, one of the heirs to billions of ...      0   
7            7  Andrew Getty, one of the heirs to billions of ...      0   
8            8  Andrew Getty, one of the heirs to billions of ...      0   
9            9  Andrew Getty, one of the heirs to billions of ...      0   
10          10  Andrew Getty, one of the heirs to billions of ...      0   
11          11  Andrew Getty, one of the heirs to billions of ...      0   
12          12  Andrew Getty, one of the heirs to billions of ...      0   
13          13  Andrew Getty, one of the heirs to billions of ...      0   
14          14  Andrew Getty, one of the heirs to billions of ...      0   
15          15  Andrew Getty, one of the heirs to billions of ...      0   

                                               sample  ref  p_agree    p_init  
0   Andrew Getty, one of the heirs to the Getty oi...    0      1.0  0.102126  
1   Andrew Getty, the grandson of oil tycoon J. Pa...    1      1.0  0.102407  
2   Andrew Getty, one of the heirs to the Getty oi...    2      1.0  0.102266  
3   Andrew Getty, one of the heirs to the Getty oi...    3      1.0  0.533854  
4   \nAndrew Getty, one of the heirs to the Getty ...    4      1.0  0.984586  
5   \nAndrew Getty, the grandson of oil tycoon J. ...    5      1.0  0.101985  
6   \nAndrew Getty, one of the heirs to the Getty ...    6      1.0  0.101633  
7   \nAndrew Getty, a member of the renowned Getty...    7      1.0  0.761402  
8   \nAndrew Getty, one of the heirs to the Getty ...    8      1.0  0.040752  
9   \nAndrew Getty, the grandson of oil tycoon J. ...    9      1.0  0.524775  
10  \nTragedy has struck the Getty family, as one ...   10      1.0  0.639710  
11  \nAndrew Getty, one of the heirs to the multi-...   11      1.0  0.769074  
12  \nAndrew Getty, one of the heirs to the Getty ...   12      1.0  0.206011  
13  \nAndrew Getty, the grandson of oil tycoon J. ...   13      1.0  0.909910  
14  \nTragedy has struck the Getty family, as one ...   14      1.0  0.176520  
15  \nAndrew Getty, one of the heirs to the Getty ...   15      1.0  0.079462

In [25]:
synth_data_train.p_init.argsort()/len(synth_data_train)

0        0.273860
1        0.177294
2        0.255983
3        0.115428
4        0.287796
           ...   
14203    0.613387
14204    0.496622
14205    0.653505
14206    0.559896
14207    0.529420
Name: p_init, Length: 14208, dtype: float64

In [10]:
pop_sync.to_dataframe().p_init.values[:100]

array([0.10212556, 0.10240709, 0.10226633, 0.5       , 0.5       ,
       0.1019848 , 0.10163288, 0.5       , 0.04075169, 0.5       ,
       0.5       , 0.5       , 0.2060107 , 0.5       , 0.17652027,
       0.07946227, 0.5       , 0.5       , 0.5       , 0.7685107 ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.67602759,
       0.5       , 0.53399493, 0.5       , 0.5       , 0.5       ,
       0.5       , 0.91019144, 0.47395833, 0.5       , 0.5       ,
       0.5       , 0.18559966, 0.5       , 0.26625845, 0.5       ,
       0.5       , 0.17856137, 0.5       , 0.12471847, 0.43517736,
       0.11563908, 0.5       , 0.5       , 0.5863598 , 0.5       ,
       0.5       , 0.62408502, 0.6352759 , 0.63590935, 0.91033221,
       0.92208615, 0.5       , 0.7417652 , 0.54103322, 0.61535755,
       0.5       , 0.5       , 0.5       , 0.5       , 0.14710023,
       0.43489583, 0.5       , 0.3042652 , 0.5       , 0.27273367,
       0.5       , 0.17609797, 0.5       , 0.5       , 0.5    

In [14]:
pop_sync_org = init_population_from_dump(synth_data_train, use_evidence=list(dtrain.df.evidence.unique()), quantile_scores=False)

In [15]:
pop_sync_org.to_dataframe().p_init.values[:32]

array([0.10212556, 0.10240709, 0.10226633, 0.5       , 0.5       ,
       0.1019848 , 0.10163288, 0.5       , 0.04075169, 0.5       ,
       0.5       , 0.5       , 0.2060107 , 0.5       , 0.17652027,
       0.07946227, 0.5       , 0.5       , 0.5       , 0.7685107 ,
       0.5       , 0.5       , 0.5       , 0.5       , 0.67602759,
       0.5       , 0.53399493, 0.5       , 0.5       , 0.5       ,
       0.5       , 0.91019144])

In [14]:
taglist = list(pop_sync.tags)

In [35]:
import numpy as np
iprob = pop_sync.get_initial_prob(taglist[8])
print(iprob)
idx_fix = np.nonzero(iprob== 0.5)[0]

[1.44498049e-07 5.04347422e-07 6.47594632e-07 5.04347242e-07
 5.00000000e-01 2.26032390e-06 6.02357608e-08 4.78509057e-06
 6.14417852e-06 6.02357536e-08 4.45084905e-07 5.71500641e-07
 5.00000000e-01 7.88926746e-06 5.04347362e-07 9.42244733e-07]


In [36]:
idx_fix

array([ 4, 12])

In [7]:
from contextlib import redirect_stdout, redirect_stderr, contextmanager
import os
@contextmanager
def suppress():
    with open(os.devnull, "w") as null:
        with redirect_stdout(null):
            with redirect_stderr(null):
                yield

In [26]:
from src.sync_data.compute_entailments import EntailmentCheckModel
from tqdm import tqdm
mynli = EntailmentCheckModel("gpt-4o")
#mynli = EntailmentCheckModel("tasksource")
for t in tqdm(pop_init.tags, desc="Computing initial certainties"):
    with suppress():
        sent_pairs = [[t[0], sentence] for sentence in pop_init[t]]
        scores = mynli.compute_scores(sent_pairs, show_progress=False)
        if t[1] == 0:
            scores[scores > 0.5] = 0.5
        else: # t[1] ==1
            scores[scores < 0.5] = 0.5
        pop_init.set_initial_prob(t, scores)

Computing initial certainties:   1%|█▍                                                                                                                   | 17/1348 [01:55<2:30:47,  6.80s/it]


KeyboardInterrupt: 

In [19]:
pop_init.to_dataframe().to_csv(f"{path}/{dtype}_{dataset}-{g}.csv")

In [9]:
from src.scripts.compute_baselines import relabel_population

In [10]:
res_popu = relabel_population(pop_init, "tasksource")

Recomputing labels: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32/32 [00:08<00:00,  3.57it/s]

join


In [12]:
tag_0_list = list([k0 for k0, k1 in pop_init.tags])

In [11]:
len(res_popu)

413

In [19]:
print(len(pop_init[(tag_0_list[2], 0)]), len(pop_init[(tag_0_list[2], 1)]))

10 16


In [20]:
print(len(res_popu[(tag_0_list[2], 0)]), len(res_popu[(tag_0_list[2], 1)]))

7 19


In [ ]:
for t in pop_init.tags:
    if pop_init.get_initial_prob(t) is not None:
        print(pop_init.get_initial_prob(t) )

In [ ]:
## Regenerate initial

In [29]:
from src.sync_data.initial_generators import FromFile
g = "QA"
mygen = FromFile(dataset="ragtruth", group=g)

In [30]:
dtrain, _ , _ = get_datasets("ragtruth", g)

Token indices sequence length is longer than the specified maximum sequence length for this model (1047 > 1024). Running this sequence through the model will result in indexing errors
Token indices sequence length is longer than the specified maximum sequence length for this model (1041 > 1024). Running this sequence through the model will result in indexing errors


In [31]:
init_popu = mygen.generate_samples(dtrain, 4)

join


In [32]:
init_popu.to_dataframe().to_csv(f"eval_run-ragtruth-{g}/seed_1-tasksource/data_iteration_0.csv", index=False)